# Site settings
title: Declaring Independence
subtitle: by SPARC
email: Greg@sparcopen.org
description: This SPARC resource provides practical, actionable guidance to scholars interested in transitioning their editorial activities from traditional subscription journals to open access alternatives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://declaring-independence.org" # the base hostname & protocol for your site
author: SPARC
plugins:
- jekyll-seo-tag

# SEO settings. More info here https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

twitter:
  username: sparc_na
logo: "/favicon.ico" # site wide logo for use on social settings
facebook:
 publisher: sparcopen
lang: en_US
logo: "{{ site.baseurl }}/favicon.ico"
# Social settings
500px_url:
facebook_url:
github_url: https://github.com/sparcopen/declaring-independence
gitlab_url:
googleplus_url:
instagram_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/sparc_na

# Sass building
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
